name: fintrack

services:
  db:
    image: postgres:18-alpine
    container_name: fintrack-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - fintrack-postgres-data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    networks:
      - fintrack-network

  flyway:
    image: flyway/flyway:13.3.0-alpine

    depends_on:
      db:
        condition: service_healthy

    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      FLYWAY_USER: ${FINTRACK_MIGRATION_USER}
      FLYWAY_PASSWORD: ${FINTRACK_MIGRATION_PASSWORD}

      FLYWAY_LOCATIONS: filesystem:/flyway/sql/migrations
      FLYWAY_DEFAULT_SCHEMA: infra
      FLYWAY_SCHEMAS: infra,identity,finance,reporting,audit
      FLYWAY_TABLE: flyway_schema_history

      FLYWAY_CONNECT_RETRIES: 10
      FLYWAY_VALIDATE_MIGRATION_NAMING: "true"
      FLYWAY_CLEAN_DISABLED: "true"

    volumes:
      - ./database/migrations:/flyway/sql/migrations:ro

    networks:
      - fintrack-network

    profiles:
      - tools

    command:
      - info

volumes:
  fintrack-postgres-data:
    name: fintrack-postgres-data

networks:
  fintrack-network:
    name: fintrack-network
    driver: bridge
