spring:
  application:
    name: fintrack-backend

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    clean-disabled: true
    validate-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

fintrack:
  security:
    jwt:
      issuer: fintrack-api
      access-token-ttl: PT15M
      refresh-token-ttl: P30D

    email-verification:
      token-ttl: PT24H

    password-reset:
      token-ttl: PT30M

    login:
      max-failed-attempts: 5
      lock-duration: PT15M
