spring:
  datasource:
    url: ${FINTRACK_DB_URL}
    username: ${FINTRACK_APPLICATION_USER}
    password: ${FINTRACK_APPLICATION_PASSWORD}

  flyway:
    url: ${FINTRACK_DB_URL}
    user: ${FINTRACK_MIGRATION_USER}
    password: ${FINTRACK_MIGRATION_PASSWORD}
    default-schema: infra
  web:
    error:
      include-message: never
      include-binding-errors: never
      include-stacktrace: never

management:
  endpoint:
    health:
      show-details: never

fintrack:
  security:
    jwt:
      secret: ${FINTRACK_JWT_SECRET}

    cors:
      allowed-origins: ${FINTRACK_CORS_ALLOWED_ORIGINS:}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
